# Generated by Django 5.2.9 on 2025-12-17 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_cart_cartitem_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_type', models.CharField(choices=[('thermal_shell', 'Thermal Shell Pack'), ('stone_bbq', 'Stone BBQ Station'), ('herringbone_deck', 'Herringbone Deck Pack'), ('industrial_shelving', 'Industrial Shelving Unit'), ('privacy_screen', 'Privacy Screen Kit'), ('green_wall', 'Green Wall Trellis Kit'), ('instant_path', 'Instant Path Aggregate Pack'), ('acoustic_pack', 'Silent Office Acoustic Pack'), ('garage_rail', 'Heavy Duty Garage Rail')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity_available', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_name', models.CharField(max_length=100)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('sold_out', 'Sold Out'), ('ended', 'Ended')], default='upcoming', max_length=20)),
                ('specifications', models.TextField(blank=True, help_text='Kit contents and specifications')),
                ('views', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, help_text='Search keywords', max_length=255)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('opened_unused', 'Opened/Unused'), ('cut_undamaged', 'Cut/Undamaged'), ('slightly_damaged', 'Slightly Damaged')], max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.IntegerField(default=50, help_text='Search radius in kilometers')),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='commerce.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.project'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_as_described', 'Not as Described'), ('damaged', 'Damaged'), ('not_received', 'Not Received'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('buyer_evidence', models.TextField(blank=True)),
                ('seller_evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('buyer_favored', 'Buyer Favored'), ('seller_favored', 'Seller Favored'), ('partial_refund', 'Partial Refund'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_type', models.CharField(blank=True, choices=[('buyer_favored', 'Buyer Favored'), ('seller_favored', 'Seller Favored'), ('partial_refund', 'Partial Refund')], max_length=20, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='commerce.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='disputes_order_i_31e8ee_idx'), models.Index(fields=['status', '-created_at'], name='disputes_status_1f4293_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('product', 'Product Listing'), ('order', 'Order/Sale'), ('user', 'User Account')], max_length=20)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('fraud', 'Fraudulent Activity'), ('quality_issue', 'Quality Issue'), ('spam', 'Spam'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_created', to=settings.AUTH_USER_MODEL)),
                ('flagged_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='commerce.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flag_type', 'status'], name='flags_flag_ty_7d75d9_idx'), models.Index(fields=['status', '-created_at'], name='flags_status_911fe7_idx')],
            },
        ),
    ]
