# Generated by Django 5.2.9 on 2025-12-16 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_add_projects_alerts_kits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('item_not_received', 'Item Not Received'), ('item_damaged', 'Item Damaged/Defective'), ('item_not_as_described', 'Item Not As Described'), ('wrong_item', 'Wrong Item Received'), ('quantity_mismatch', 'Quantity Mismatch'), ('payment_issue', 'Payment Issue'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Detailed explanation of the dispute')),
                ('buyer_evidence', models.TextField(blank=True, help_text="Buyer's evidence/notes")),
                ('seller_evidence', models.TextField(blank=True, help_text="Seller's evidence/notes")),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('buyer_favored', 'Resolved - Buyer Favored'), ('seller_favored', 'Resolved - Seller Favored'), ('partial_refund', 'Resolved - Partial Refund'), ('closed', 'Closed')], default='open', max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='commerce.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('product', 'Product Listing'), ('order', 'Order/Sale'), ('user', 'User Account')], max_length=20)),
                ('reason', models.CharField(choices=[('fraudulent', 'Fraudulent Activity'), ('misleading', 'Misleading Information'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('wrong_category', 'Wrong Category'), ('duplicate', 'Duplicate Listing'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Detailed explanation of the flag')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags_received', to=settings.AUTH_USER_MODEL)),
                ('flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='commerce.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
